### ISSUE TITLE
Fat Javadoc Jar

### ISSUE THREAD

**Issue by OroArmor** [QuiltMC/quilt-standard-libraries#101]
A javadoc jar that has javadocs for all the modules in QSL. Will increase API discovery and easier to link to for basic docs

**Comment by md5** [comment]
I was just looking for this and it looks like the published JAR file is empty for `5.0.0-alpha.1+1.19.4-pre3`: https://maven.quiltmc.org/repository/release/org/quiltmc/qsl/5.0.0-alpha.1+1.19.4-pre3/qsl-5.0.0-alpha.1+1.19.4-pre3-fat-javadoc.jar/

It looks like `4.0.0-beta.9+1.19.3` is OK: https://maven.quiltmc.org/repository/release/org/quiltmc/qsl/4.0.0-beta.9+1.19.3/qsl-4.0.0-beta.9+1.19.3-fat-javadoc.jar/
