### ISSUE TITLE
Block Items don't get added to modded creative tabs.

### ISSUE THREAD

**Issue by ghost** [QuiltMC/quilt-standard-libraries#103]
This is how Expanded Storage looks on quilt, note the scroll bar is scrollable as if the slots are populated. However the slots where the chests / barrels should be are visually and actually empty.
![image](https://user-images.githubusercontent.com/5214513/164339408-3b3b8be8-0c04-414d-a37a-e7652fbc016d.png)
In contrast this how the mod looks on fabric:
![image](https://user-images.githubusercontent.com/5214513/164339391-b0ed1246-14bb-4bec-8337-f7657e3df4f1.png)

Edit: from discord this sounds like an issue with modded block items only.

**Comment by LambdAurora** [comment]
This has been isolated to `quilt_registry` being missing in Quilted FAPI distribution.

**Comment by LambdAurora** [comment]
Fixed in Quilted FAPI 1.0.0-beta.8+0.51.1-1.18.2
