### ISSUE TITLE
Multiple calls to `BlockRenderLayerMapImpl` will cause `NullPointerException`

### ISSUE THREAD

**Issue by OroArmor** [QuiltMC/quilt-standard-libraries#115]
https://github.com/QuiltMC/quilt-standard-libraries/blob/868b33d9d6fd4a244c0aeae03dd88882a0f3bd09/library/block/block_extensions/src/main/java/org/quiltmc/qsl/block/extensions/impl/client/BlockRenderLayerMapImpl.java#L43-L55

Probably fine, but could cause an issue

**Comment by EnnuiL** [comment]
This has been addressed since 1.1.0-beta.13
