### ISSUE TITLE
Publish to Curseforge

### ISSUE THREAD

**Issue by Madis0** [QuiltMC/quilt-standard-libraries#118]
[CurseForge allows Quilt mods now.](https://twitter.com/CurseForge/status/1529766591403118598) 
While they don't support Quilt in their launcher yet, publishing to CurseForge would help people become aware that Quilt is a thing.

**Comment by TheKodeToad** [comment]
It would also be useful so you can add QSL as a dependency.

**Comment by EnnuiL** [comment]
Quilted Fabric API, which is the mod responsible for distributing QSL (therefore, QFAPI / QSL), has been released on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/qsl/)
