### ISSUE TITLE
Fabric Client dosn't like Quilt Server

### ISSUE THREAD

**Issue by greysilly7** [QuiltMC/quilt-standard-libraries#130]
When I join my Quilt server from my fabric client (Fabulously Optimized) I get "Registry remapping failed: Received ID map for Minecraft:command_argument_type contains IDs unknown to receiver! - quilt_command:enum"

**Comment by greysilly7** [comment]
Also, this is the error in my client's logs 
https://paste.gg/p/greysilly7/1c30a033d6e34b6987f10497c413c2cc

**Comment by JieningYu** [comment]
why don't use Quilt Client directly

**Comment by greysilly7** [comment]
1. I can't just force everyone on my server to either use Quilt or vanilla
2. I am using a modpack and don't really wanna install Quilt and potentially break stuff

**Comment by JieningYu** [comment]
Why you can't force the players to use Quilt? The server is yours.

**Comment by greysilly7** [comment]
That's called being a terrible server owner, and everyone should get to choose what they want to use!

**Comment by LambdAurora** [comment]
@JieningYu I don't think what you're suggesting is a reasonable "fix".

In the end this is a bug that shouldn't happen in our opinion.

**Comment by jpenilla** [comment]
This looks similar to https://github.com/KyoriPowered/adventure-platform-fabric/issues/39 - I updated colonel's code for adventure-platform-fabric's proposes to fix that here: https://github.com/KyoriPowered/adventure-platform-fabric/pull/40, those changes should be adaptable to Quilt command's use of colonel code to fix this issue as well.

**Comment by LambdAurora** [comment]
> This looks similar to [KyoriPowered/adventure-platform-fabric#39](https://github.com/KyoriPowered/adventure-platform-fabric/issues/39) - I updated colonel's code for adventure-platform-fabric's proposes to fix that here: [KyoriPowered/adventure-platform-fabric#40](https://github.com/KyoriPowered/adventure-platform-fabric/pull/40), those changes should be adaptable to Quilt command's use of colonel code to fix this issue as well.

Uh, so instead of registering into the registry you emulate an entire registry?
It may works, but our thing works too, it only breaks with Fabric registry sync.

I think I would prefer to get registry sync merged in, which will offer options to exclude entries from registry syncing, which might just be enough for our use-case?
The suggested solution seems to have a higher maintenance cost.

**Comment by EnnuiL** [comment]
Currently patched on QFAPI itself; Once the Quilt Registry Sync is ready, QSL will have a better solution to that
