### ISSUE TITLE
Documents don’t show basic blocks

### ISSUE THREAD

**Issue by Danjhop4** [QuiltMC/quilt-standard-libraries#157]
With the item it shows a example of a pick axe item can you add a basic example of items and blocks

**Comment by Danjhop4** [comment]
Does not load

**Comment by LambdAurora** [comment]
Hello,

I've skimmed a bit the javadocs to find what you were talking about.
Sadly I have not found the mentioned basic example of item.

If you can please indicate in which class you found it so we can get a clearer idea of what we should expect.

**Comment by Danjhop4** [comment]
I took it from the GitHub for item api testmod

**Comment by LambdAurora** [comment]
Testmods are not public documentation but rather tests to make sure everything is working as intended.

Sure they can be used to look into how to use some stuff, but that's not their primary goal.
Javadocs and the modder wiki should be the places for that instead.

**Comment by Danjhop4** [comment]
Not anything for that yet

**Comment by Danjhop4** [comment]
Tried asking on discord

**Comment by Danjhop4** [comment]
Crash’s game using 1.19.1 if that helps

**Comment by Danjhop4** [comment]
Deleted the the folder I made

**Comment by gdude2002** [comment]
If you're working on a mod of your own, this isn't the right place for this issue. For the time being, you can get support on Discord or the forums - Quilt is still in beta, so our documentation isn't ready yet.

**Comment by Danjhop4** [comment]
I got that

**Comment by Danjhop4** [comment]
Is the APIs stuff mainly from fabric
