### ISSUE TITLE
The DFU module makes LazyDFU useless on Quilt

### ISSUE THREAD

**Issue by TheGlitch76** [QuiltMC/quilt-standard-libraries#169]
The current DFU module always queries the vanilla schema during entrypoints. This makes mods like LazyDFU effectively useless, because the schema now always has to be built on Quilt.

The code should be changed so that the Vanilla schema is not queried until and unless absolutely necessary.

**Comment by Leo40Git** [comment]
The problem is that the Vanilla schema is required to even _start_ building modded DataFixers, unless we find another way to get all the Vanilla DFU types...

**Comment by EnnuiL** [comment]
LazyDFU wasn't affected by the DFU library and still remained functional; An unrelated issue with DataBreaker, however, has been fixed
