### ISSUE TITLE
Ability to exclude certain additions from registry sync

### ISSUE THREAD

**Issue by samolego** [QuiltMC/quilt-standard-libraries#2]
(Following up the #1.)
> It'd also be nice to be able to disable certain stuff from registry sync, even if added to registry.

As stated there, having "forced" registry sync (like with Forge if I understood correctly) would mean that players with vanilla clients can't connect to a server if it has modded registries (contains new blocks, items, entites, etc.). This is fine in most use cases, but with some mods, it would be beneficial to mark certain additions in registry as "not needed on client".

## Use cases?

It's the server-side mods that would benefit from that, as they can add new items / entites / etc. with unique abilities but show them as vanilla items / entities on clients.

**Comment by Waterpicker** [comment]
Interstingly. I have a use case for that's client side. ^^

**Comment by i509VCB** [comment]
@Waterpicker not sure what benefit there would be to C2S registry sync? Anyways the plan I already see is that the server may not require the client to have some registry entries

**Comment by EnnuiL** [comment]
Oh dear, this is a quite ancient issue; I believe that Quilt Registry Sync has addressed this with the addition of optional entries/registries, as well as the possibility of skipping entries
