### ISSUE TITLE
REAs have mysterious issues when modded tags and items are added to it

### ISSUE THREAD

**Issue by EnnuiL** [QuiltMC/quilt-standard-libraries#210]
This appears to affect both the data-driven way and the code one.

Case 1 (Crooked Crooks vs Promenade):
With Crooked Crooks' `crooked_crooks:crook_effective` REA, on [its current state](https://github.com/EnnuiL/CrookedCrooks/blob/71e44f45c199c064a8cffff18ce9964cd3aa3a6f/src/main/resources/data/crooked_crooks/attachments/minecraft/block/crook_effective.json), it works properly when Promenade is absent, but when it's installed, its leaf piles are absent from the REA until a `/reload` is done (Promenade leaves are included under `#minecraft:leaves` though). When replacing the `#promenade:leaf_piles` tag with the `promenade:oak_leaf_pile` item, it surprisingly results into only the Oak Leaf Pile being present on the entire REA, with everything else going *poof*; Replacing it with Aurora's Decorations' `aurorasdeco:sleeping_bag/red` item, however, results into it not appearing at all too, like the leaf pile tags, therefore discarding the hypothesis that this only affects Fabric mods.

Case 2 (Quilt Item Content Registries vs BYG):
An user had reported on Quiltcomm about BYG entries not working under Quilt's ICR bridge, with attempts to circumvent code issues with a data pack failing to do anything. The data pack had specified all the relevant BYG items, and despite that, it didn't work anyway. Vanilla entries were intact.

Conclusion? i unfortunately have no idea what's the exact cause of this all, i suspected fabric shenanigans, but it definitely isn't that
(also, why the heck did i use periods on the main content)

**Comment by EnnuiL** [comment]
After a lot of bisecting, PR #128 was determined to be the culprit

**Comment by EnnuiL** [comment]
While the commit has marked it as closed, I need confirmation that the issue's dead; I need further testing

**Comment by EnnuiL** [comment]
On attempting to reproduce this issue with versions after the REA sync fix with this computer, I completely failed to reproduce it... ~~That's it, I'm calling the Ghostbusters~~

**Comment by EnnuiL** [comment]
On attempting to reproduce it on the original PC? The issue wasn't present; I assume this is how I have managed to fool myself into thinking I have fixed with an issue with a broken "fix"; but yeah, i still wonder when exactly it was fixed; unfortunately, i don't have enough energy to investigate that

but yeah! this issue has been fixed somehow!

**Comment by Leo40Git** [comment]
Oh.
Uh.
YAY!
