### ISSUE TITLE
Registry Entry Attachment API Conflicts With Fabric Mod

### ISSUE THREAD

**Issue by sylv256** [QuiltMC/quilt-standard-libraries#215]
# Description
I'm not sure if this is because it is using ARRP or something, but the latest QFAPI/QSL seems to throw a fit when using the latest port of Phonos to 1.19.2. The last version of QFAPI/QSL that doesn't do this is `4.0.0-beta.7+0.59.0-1.19.2`. I suspect this is an issue with QSL or QFAPI, because the REA API seems very buggy, and Phonos doesn't do anything weird with registries (besides ARRP). Currently, the port of Phonos can be found in this repository: https://github.com/Motschen/Phonos/tree/1.19

# Logs
https://mclo.gs/QKbiIkd

**Comment by LambdAurora** [comment]
This may be caused by the mod registering something into a REA before registering the game object into its registry.

**Comment by OroArmor** [comment]
Please have the mod use `OxidizableBlocksRegistry` and remove the mixin plugin. The code that you have linked is extremely fragile and should not be used.
