### ISSUE TITLE
Screen API crashes after ALLOW_KEY_PRESS event cancels the keypress

### ISSUE THREAD

**Issue by BasiqueEvangelist** [QuiltMC/quilt-standard-libraries#223]
The [relevant code](https://github.com/QuiltMC/quilt-standard-libraries/blob/1.19/library/gui/screen/src/main/java/org/quiltmc/qsl/screen/mixin/client/KeyboardMixin.java#L34-L50) tries to cancel a method without a `cancellable = true`.
This causes a nasty crash with any mod that uses the ALLOW_KEY_PRESS event.
Here's an example: https://cdn.discordapp.com/attachments/1046181424765616158/1046181425172455524/crash-2022-11-26_22.46.44-client.txt

**Comment by LambdAurora** [comment]
This already has been reported as #217.
