### ISSUE TITLE
Possible crash report info apis

### ISSUE THREAD

**Issue by i509VCB** [QuiltMC/quilt-standard-libraries#23]
At the moment the only thing crash report info does is add quilt mods to the system details log. However I see it as being useful to possible allow other mods to add to the system details via a public api.

Some immediate use cases that come to my head could be:
- Mods with native libraries dumping information about said libraries.
- Mods heavily modifying the rendering system such as Sodium and Blaze4D being able to dump info about the OpenGL capabilities/Vulkan extensions that are available/enabled.
- Something like optifabric could insert info about the version of optifine in use.

**Comment by OroArmor** [comment]
Seems like people like this idea. Plus it doesn't really hurt as it's only a new class or two for the crash report api. Might be best in an entry point as then it's not a runtime dependency
