### ISSUE TITLE
Commands module causes client to be unable to connect to 1.19.2 ViaVersion server

### ISSUE THREAD

**Issue by triphora** [QuiltMC/quilt-standard-libraries#232]
![image](https://user-images.githubusercontent.com/60205699/206598816-0615811d-08ad-4e19-9397-d84918c77037.png)
Log: https://mclo.gs/WOfwu1v
As you can see from the mods list in the log, I only have the QSL modules necessary to load the commands module.

To reproduce:
1. Add commands module (and its dependencies) to a 1.19.3 instance
2. Attempt to connect to a 1.19.2 Paper/Waterfall server supporting 1.19.3 via ViaVersion
3. See disconnection message above

Disabling the commands module does not cause the disconnection shown in the screenshot above.

Suspected cause based on a cursory search: [ServerArgumentType.java#L115](https://github.com/QuiltMC/quilt-standard-libraries/blob/1.19.3/library/management/command/src/main/java/org/quiltmc/qsl/command/api/ServerArgumentType.java#L115)

**Comment by LambdAurora** [comment]
This has been fixed with eb0acc171a058e7fc9de02bf0ea57a388013a530.
