### ISSUE TITLE
Stone slab duplication via stonecutter

### ISSUE THREAD

**Issue by Lentern** [QuiltMC/quilt-standard-libraries#234]
On 1.19.2, placing a stack of smooth stone blocks into a stonecutter and crafting them all into slabs, you are then given the option to create infinite slabs. Only happens with QSL installed.
This is fixed in QSL for 1.19.3 but the fix should probably be backported.

https://user-images.githubusercontent.com/73498459/208220595-a96883d8-c7e2-432d-af66-7f265fb0cc75.mp4

**Comment by eristhea** [comment]
hi! seeing as quilt is still in beta, we're not investing too much of our time in backports. sorry!
