### ISSUE TITLE
`StonecutterOutputSlotMixin` can cause index out of bounds exceptions

### ISSUE THREAD

**Issue by Jamalam360** [QuiltMC/quilt-standard-libraries#238]
This may be a mod incompatibility. The mod table is included in the crash log.

Occurs when taking **specific recipes** out of the stone cutter. In this example, the crash is when cutting Consistency+ cobbled andesite into normal andesite.

[Crash log](https://haste.jamalam.tech/fuyepiyipe.yaml)

Side note: it'd be nice to have prefixed mixins. I had to do an export to find which mod was injecting where and causing the crash.

**Comment by Jamalam360** [comment]
All of the crashes that have been reported to me so far are with Consistency+ stonecutting recipes

**Comment by TropheusJ** [comment]
Fix is unreleased, not a qsl issue https://github.com/ConsistencyPlus/ConsistencyPlus/issues/137

**Comment by Jamalam360** [comment]
Thanks :)
