### ISSUE TITLE
Quilt Renderer API vs FREX - Request for Comments

### ISSUE THREAD

**Issue by grondag** [QuiltMC/quilt-standard-libraries#25]
**Background**
I intend to port the Fabric Rendering API to Quilt with some improvements.  Some of those improvements will come from [FREX](https://github.com/grondag/frex).  Currently, some important FREX interfaces inherit from Fabric API interfaces.

While Quilt is hopefully going to be more expansive I don't assume it will encompass all current and future features in FREX.  Thus, FREX remains important to me as a separate library/API because I'm committed to maintaining separation of specification and implementation for Canvas and, someday, other renderers that want to support an open standard.

This means FREX will continue as a superset of both FRAPI and Quilt and needs to be compatible with either.

I plan to handle this by changing FREX so that it no longer inherits from either Fabric or Quilt but instead includes a wrapper for whichever is present for API consumers.  For API implementations like Canvas the problem is a little messier, but I'll figure something out.

**Questions to Be Answered**

If FREX is a compatible superset of FRAPI and Quilt and offers features not available in either, it seems like the logical dependency to use for anyone who isn't skittish about 3rd-party libraries.

This creates some unfortunate redundancy, but many devs _are_ skittish about "unofficial" libraries, so:

1) Is it a correct assumption that Quilt should incorporate a non-dependent subset of FREX features, vs just directing people to use FREX?

2) If so, what are the guiding principles for which features Quilt should have?  For Fabric, one important guideline was that if it would require a very invasive change to implement, it should probably be out of scope.  A similar heuristic is to avoid features that can't be readily implemented and maintained in the default renderer.  (That puts the GLSL Shader API right out.)

3) Should Quilt implement FRAPI compatibility even though FREX will be available for the same purpose?  It means redundant work (that mostly falls on me) but seems necessary because of reluctance in the community to depend on "non-official" libraries and to simplify distribution and dependency management for anyone who just needs the core features.

Thank you in advance for your input.

**Comment by grondag** [comment]
I forgot to mention - FREX includes a way for API consumers to query which features are available in the current renderer.  Not all features will be required.  Thus, if we did somehow land on "just use FREX" as the decision, Quilt could still bundle a light-weight indigo-like renderer that only implements the most important features.

**Comment by i509VCB** [comment]
> Is it a correct assumption that Quilt should incorporate a non-dependent subset of FREX features, vs just directing people to use FREX?

My interpretation of this question is do we provide a rendering api or leave that all to frex? Unsure if I got that right

> If so, what are the guiding principles for which features Quilt should have?

We haven't codified this yet, but I would like to see it as `widely useful`. Even if width means only one other renderer implementation exists, I'd say it's good enough to be somewhat considered.

> For Fabric, one important guideline was that if it would require a very invasive change to implement, it should probably be out of scope.

Unless something is truly broken I'd try to avoid breaking too much. However the other consideration I'd have is what is the minimum level of entry for a feature, if it's like resource loader where there is a lot to cover, I'd argue it being a little more invasive is fine?

> Should Quilt implement FRAPI compatibility even though FREX will be available for the same purpose?

I believe our plan to to keep the Fabric API compatibility in a separate repository. Haven't started that yet or fully formed that idea.

**Comment by grondag** [comment]
> My interpretation of this question is do we provide a rendering api or leave that all to frex? Unsure if I got that right

More or less.  My assumption is yes.  It just seems like a lot of redundant work because FREX will still be a thing.  If I had it to do over I'm not sure I'd ever have pushed for FRAPI in the first place because of the redundancy.  On the other hand, having some minimum API in the "official" distribution does help with adoption.

**Comment by i509VCB** [comment]
At that point then the question is where does the FREX 2 go? Don't know whether it's made part of QSL's rendering library, a separate repository in Quilt's GitHub organization, another organization, your account, etc...

Given any of the latter 3 cases, those may depend on QSL as well, removing some of the need on the strict QSL rule where you can only depend on things in same library or core.
