### ISSUE TITLE
Duplication bug with furnace inputs and recipe remainders

### ISSUE THREAD

**Issue by ramidzkh** [QuiltMC/quilt-standard-libraries#251]
QSL's recipe remainder hooks add remainder support to furnace inputs; this breaks smelting recipes that use water buckets as inputs - vanilla does not compute the remainder there, so the bucket should be destroyed. Quilt adds a remainder bucket instead, causing a duplication bug with MI.

https://github.com/AztechMC/Modern-Industrialization/blob/2f46d55691c1381b206adaefd1b91d794bf91918/src/main/resources/data/modern_industrialization/recipes/vanilla_recipes/steam_bucket.json

**Comment by OroArmor** [comment]
With the new ways to read recipes in 1.20.2, I think there is a fairly simple way of doing this with a simple optional added field to the json at the end that allows disabling the remainder(s) in the recipe.

**Comment by OroArmor** [comment]
I have thought of a better solution. A fix will come soon.
