### ISSUE TITLE
(1.19.2) QSL Makes Nether Woods Burnable

### ISSUE THREAD

**Issue by Noobulus** [QuiltMC/quilt-standard-libraries#256]
With QFAPI installed, Nether woods (ex. warped & crimson planks) are assigned the same furnace burn time as regular planks.

This does not occur with just the Quilt Loader installed or with Fabric + FAPI.

**Comment by OroArmor** [comment]
Uh this should not be happening. do you have any other mods or datapacks installed?

**Comment by Noobulus** [comment]
Nope, just Quilt and QFAPI in a fresh instance.

**Comment by OroArmor** [comment]
Alright thanks. Will look into this

**Comment by EnnuiL** [comment]
This issue has been fixed through a temporary solution for filtering out these entries; We plan to revisit that with a better solution later on
