### ISSUE TITLE
Make a general API for modifying data driven values

### ISSUE THREAD

**Issue by OroArmor** [QuiltMC/quilt-standard-libraries#263]
This api should have two aspects:
1. Load/Merge data from multiple json files
2. Allow modification of parsed objects

A basic example of this is the Fabric Loot Table api, which allows modification of loot tables in code, but not with json.

**Comment by DevPJ9** [comment]
Hello @OroArmor I would like to work on this.

**Comment by EnnuiL** [comment]
PR #264 has been merged and will be released publicly soon, am closing this
