### ISSUE TITLE
[Crash] Crash on startup.

### ISSUE THREAD

**Issue by DanMeadWasTaken** [QuiltMC/quilt-standard-libraries#268]
I'm getting a crash on startup, and can't make head's or tails or the log, it seemed like me to point towards quilt. But if someone could point me in the right direction before i gotta just rip out mods one by one until it works, the help would be much appreciated.

https://mclo.gs/ZZem0UZ

**Comment by OroArmor** [comment]
Remove the `Chunky extended` mod. It is broken.
