### ISSUE TITLE
The new registry sync format.

### ISSUE THREAD

**Issue by i509VCB** [QuiltMC/quilt-standard-libraries#28]
This issue pertains to discussion about the new registry sync format.

There have been a few issues with the registry sync fabric uses that causes it to reach the maximum packet size quickly.

A few of these issues include:
- The overhead of the NBT format in serialization for the packet
- The inclusion of the namespace inside all Minecraft namespaced identifiers.
- The map structure of the packet using key -> value for every namespace and string takes up extra room.
- Where a sequence of all identifiers inside the packet are of the same namespace, the namespace is included in the identifier.
- Some registries get many more registrations than others, meaning just a few registries in the same packet fill up the entire payload of the packet.
- Overloaded registries cannot be split if they hit the max payload size.

Given the above issues, I feel we can greatly reduce the size of the packet with some optimizations.

**Comment by Leo40Git** [comment]
Suggestion for a "common registry" packet structure:
```c
struct rsync_packet_common {
    mc_id registry;
    int namespace_count;
    rsync_packet_common_namespace[] namespaces;
}

struct rsync_packet_common_namespace {
    int size;
    string namespace;
    string[] paths;
    int[] ids;
}
```
This is efficient for things like the block/item registries which get many registrations in many namespaces (the segmented nature allows multiple namespaces to be sent in one packet, should the namespaces be small enough).

**Comment by LambdAurora** [comment]
Registry synchronization PR has been merged, which comes already with a new format for Quilt.
