### ISSUE TITLE
Update to latest Quilt Loader 0.18.x

### ISSUE THREAD

**Issue by EnnuiL** [QuiltMC/quilt-standard-libraries#285]
Currently, this is blocked on a loader issue that stops the tests from running; There's not much we can do until that is solved

**Comment by TheGlitch76** [comment]
0.18.9 should fix every issue we've been seeing:
https://github.com/QuiltMC/quilt-standard-libraries/commit/f63fc31b06a106a1467e24f69353ffbc3216c5b0
