### ISSUE TITLE
[1.19.4] ServerLifecycleEvents.READY never fires when carpet mod is installed

### ISSUE THREAD

**Issue by Wesley1808** [QuiltMC/quilt-standard-libraries#289]
This causes other mods to find themselves in illegal states that were supposed to be setup on the server started / ready event.

I think this is most likely happening because [carpet](https://github.com/gnembon/fabric-carpet/blob/f98c2409be42de6b0b02c2499244dfddd2e9a1e6/src/main/java/carpet/mixins/MinecraftServer_tickspeedMixin.java#L84) is injecting its own tick loop at the same target as [QSL](https://github.com/QuiltMC/quilt-standard-libraries/blob/1.19.4/library/core/lifecycle_events/src/main/java/org/quiltmc/qsl/lifecycle/mixin/MinecraftServerMixin.java#L46) does its ready event, making it a race for whoever gets priority on the `@Inject`.

If carpet's tick loop gets priority, the ready event will only ever fire once the server shuts down.
Note: this only occurs on quilt, fabric is unaffected.

**Comment by TheGlitch76** [comment]
Carpet will need to fix this issue on their end.

**Comment by LambdAurora** [comment]
Seems to have been fixed in Carpet.
