### ISSUE TITLE
Quilt 0.18.10 incompatible with Extended Block Shapes 2.0.0, on 1.19.4

### ISSUE THREAD

**Issue by dizzydizzee** [QuiltMC/quilt-standard-libraries#296]
The game crashes before managing to startup, caused by Extshape 2.0 - The mod works perfectly on Fabric loader, but fails to start with Quilt.

Using MultiMC launcher, instance works perfectly with all mods except Extshape - have opened issue with mod creator as well.

Crash Log: [https://paste.ee/p/yJQy8](https://paste.ee/p/yJQy8)

**Comment by OroArmor** [comment]
This paste no longer exists.
