### ISSUE TITLE
Consider tag mirrors for REAs

### ISSUE THREAD

**Issue by EnnuiL** [QuiltMC/quilt-standard-libraries#304]
We should consider having a way of REAs to provide a list of entries as a tag, with the usecase in mind being the enchanting boosters REA, which will now conflict with Vanilla's own tag

**Comment by LambdAurora** [comment]
You can already give it a tag with a value of 1 for the enchanting boosters, this was already mentioned multiple times....

**Comment by EnnuiL** [comment]
Yes but that's a bodge, what I mean is the vice-versa: the REA would be the source of truth and the tag would only be a reflection of it, a tag mirror of a REA, if you will; The intention is to yeah, do things properly, because folks will definitely use the tag and not the REA in the end, especially since tags has a better level of integration than REAs (example: you can't use an entity type REA on entity selectors and such)

**Comment by LambdAurora** [comment]
imo that becomes complex way too quickly for tags, for now modders and data-pack makers should be expected to modify the tag to deal with the feature, and the REA to precise a value.

**Comment by lukebemish** [comment]
Ideally, and I don't know how feasible this is, both would provide true responses for any given block. For instance, any block with a value through the REA would be in the tag and anything in the tag but not explicitly declared in the REA would have a value in the REA of 1 (or whatever the default is). I *think* the second part might already be possible? I'm not sure. This proposed change would allow the first one, though, and also be useful in general cases; if I wanted to make a worldgen feature or recipe or whatever targeting blocks/items with a given REA controlled property, for instance, or if I wanted to nest inside another tag all blocks/items with a given property

**Comment by EnnuiL** [comment]
> imo that becomes complex way too quickly for tags, for now modders and data-pack makers should be expected to modify the tag to deal with the feature, and the REA to precise a value.

hm, fair enough; i guess we can think about this stuff later
