### ISSUE TITLE
Quilt maven doesn't contain any QSL jar

### ISSUE THREAD

**Issue by deirn** [QuiltMC/quilt-standard-libraries#308]
The only available jar is the Javadoc jar, in both [release](https://maven.quiltmc.org/repository/release/org/quiltmc/qsl/5.0.0-beta.6+1.19.4/) and [snapshot](https://maven.quiltmc.org/repository/snapshot/org/quiltmc/qsl/5.0.0-beta.7+1.19.4-SNAPSHOT/) maven.

**Comment by LambdAurora** [comment]
QSL doesn't distribute any fat jar of its releases, only modules are available, the base qsl publication only contains javadoc and maven metadata to import all modules in a Gradle project.

Quilted Fabric API is the "bundled" distribution of both QSL and Quilt's Fabric API fork.

**Comment by deirn** [comment]
The modules also only has the pom file published. https://maven.quiltmc.org/repository/release/org/quiltmc/qsl/block/5.0.0-beta.6+1.19.4/

I noticed this in the middle of a [build](https://github.com/badasintended/wthit/actions/runs/5031341851), it seems to be missing after the 1.19.2 task for some reason.

**Comment by deirn** [comment]
Oops, I just noticed that one of my dependencies maves is down... https://dvs1.progwml6.com/files/maven/

Maybe it's the cause of the error instead. Sorry, gradle sucks.

**Comment by LambdAurora** [comment]
> The modules also only has the pom file published. https://maven.quiltmc.org/repository/release/org/quiltmc/qsl/block/5.0.0-beta.6+1.19.4/

For the sake of information, what this link points to is one of the QSL libraries, not a module!

QSL structures its modules into libraries, libraries only exist in the repo's directories structures and as meta-dependencies on maven. All the actual modules should have JARs in their maven tree.
