### ISSUE TITLE
QSL for 1.20-pre5 rejects to run on 1.20-pre6

### ISSUE THREAD

**Issue by teddyxlandlee** [QuiltMC/quilt-standard-libraries#309]
When I run 1.20-pre6 with `qfapi-7.0.0-alpha.1_qsl-6.0.0-alpha.3_fapi-0.81.3_mc-1.20-pre5.jar`, the game fails to start.

The libraries restrict Minecraft version to a specific pre-release version, like this:
```json
                 "depends": [
			{
				"id": "quilt_loader",
				"versions": ">=0.18.10"
			},
			{
				"id": "minecraft",
				"versions": "=1.20-beta.5"
			},
			{
				"id": "quilt_base",
				"versions": ">=6.0.0-alpha.3+1.20-pre5"
			}
		]
```
I think this might be a gradle script problem, but I couldn't find where the QMJ generator is defined.

Anyway, I think the restriction of `minecraft` version should be defined elsewhere, instead of using an `=` sign following a specific version no matter whether it is snapshot.

**Comment by OroArmor** [comment]
Closing as this is 3 months old
