### ISSUE TITLE
not api (no were else to place this discord triggers family safe)

### ISSUE THREAD

**Issue by Danjhop4** [QuiltMC/quilt-standard-libraries#314]
the pineapple page on discord cause microsoft familly safe to lock out can you fix that
![lock out](https://github.com/QuiltMC/quilt-standard-libraries/assets/106870098/611494da-e13d-497b-a8be-00662200c4e5)
sorry in advanced for off topic

**Comment by Danjhop4** [comment]
fabric discord banned me randomly 
and i need discord to help me

**Comment by Danjhop4** [comment]
claims i spammed i only do that when its needed i dont like that
and the spam on github was me asking why i got banned

**Comment by Danjhop4** [comment]
i have spammed when forced to do so

**Comment by LambdAurora** [comment]
Just don't click on the pineapple channel?

There's only one picture of a pineapple in it. The behavior of Microsoft Family Safe stuff is not our problem.

This is not the place to ask about this, and spamming will not resolve your problem.
