### ISSUE TITLE
QFAPI could not load on latest Quilt

### ISSUE THREAD

**Issue by Muska-Ami** [QuiltMC/quilt-standard-libraries#319]
The bug report tells me to use the latest version 0.19.2, however I have updated to beta.7 XD.
```
https://pastebin.com/RyeRRFes
```

![image](https://github.com/QuiltMC/quilt-standard-libraries/assets/79651409/9e32ae0c-f277-4812-9acb-767983ba5827)
![image](https://github.com/QuiltMC/quilt-standard-libraries/assets/79651409/fb733a38-f821-4c29-99c6-0c466de5cc99)

**Comment by tenshiaka** [comment]
same issue here

**Comment by OroArmor** [comment]
There was an issue with the latest version of `quilt_loader` not appearing in launchers. It should be fixed now.
