### ISSUE TITLE
Conventions for QSL

### ISSUE THREAD

**Issue by i509VCB** [QuiltMC/quilt-standard-libraries#32]
This issue is here to iron out the conventions for QSL that will eventually end up in the CONTRIBUTING.md file.

These conventions should dictate the standard to which QSL's codebase is to be developed by. A few examples of possible categories for conventions include:
- naming conventions
- big boo boos you should avoid
- how to approach writing documentation
- code structure
- general styling guidelines (I intentionally chose general since we have no suitable autoformatter to enforce these guidelines).

Commenters should go into detail on conventions that should be considered or current conventions to be amended.

**Comment by TehcJS** [comment]
is there an RFC for this?

**Comment by sylv256** [comment]
basic naming conventions draft
# Naming Conventions
## Case
Field, method, and local variable names should always use `camelCase`, and class names should use `PascalCase`.
## Preferred Language Dialect
When naming identifiers, **American English** (replace with final) should be used. Mixing dialects can cause inconsistencies and confusion for maintainers and developers.

**Comment by TheGlitch76** [comment]
Do we want get/is prefixes for getters, or are we following the record style?

**Comment by LambdAurora** [comment]
> Do we want get/is prefixes for getters, or are we following the record style?

Imo it depends, for immutable stuff, record-style for sure, else there's cases where not having a prefix is really ambiguous, especially some boolean stuff.

**Comment by der-teufel-programming** [comment]
In my experience get/is getters improve readability and as @LambdAurora said, getters could be confused with other methods easily in some contexts

**Comment by LambdAurora** [comment]
Recent updates to the CONTRIBUTING file introduced conventions, I believe this is solved now. Most of it come from Quilt Mappings to keep consistency across both projects.
