### ISSUE TITLE
Equipment slot item setting only applies for instances of Equipable

### ISSUE THREAD

**Issue by TropheusJ** [QuiltMC/quilt-standard-libraries#320]
Mixin export:
![image](https://github.com/QuiltMC/quilt-standard-libraries/assets/60247969/be209e7b-8670-4b94-a249-891aa48a940b)

This makes the API useless, since Equipable must be implemented anyway, and providing an EquipmentSlot is its entire purpose.
Fixing this should be as simple as moving the inject point in LivingEntityMixin.

**Comment by EnnuiL** [comment]
To be fixed on the next update!
I have decided to keep Equippable's provided slot a priority though; if we decide to flip the priority? some extra work will be needed
