### ISSUE TITLE
Overworld is removed from world_gen_settings when QuiltDataFixes used with Lithium and custom ChunkGenerator class

### ISSUE THREAD

**Issue by quiqueck** [QuiltMC/quilt-standard-libraries#324]
I opened an Issue for this over at Lithium, but since I am not sure exactly what is causing the issue, I'll repost it here:

CaffeineMC/lithium-fabric#480

The original report was this issue: quiqueck/BCLib#113

**Comment by TheGlitch76** [comment]
WilderWilds is using its own port of Quilt DFU API; it is disabled on our (QSL)'s end and not usable by mods through QSL or QFAPI, because the API is flawed!

**Comment by quiqueck** [comment]
Oh Sorry, I didn't know that. I'll add it to WilderWilds then...
