### ISSUE TITLE
Incorrect translation method causes "%s" disconnect errors

### ISSUE THREAD

**Issue by TropheusJ** [QuiltMC/quilt-standard-libraries#325]
I've noticed this disconnect screen appearing somewhat often:
![image](https://github.com/QuiltMC/quilt-standard-libraries/assets/60247969/9615dd4d-54ff-4a91-8348-1e48a1cf3e3f)

I found a case where a placeholder is not being filled in, and the content is being used as a fallback instead, [here](https://github.com/QuiltMC/quilt-standard-libraries/blob/9ff2e97b18e357b5b56f4c280e48ff34b18ebf70/library/core/networking/src/main/java/org/quiltmc/qsl/networking/mixin/ClientConnectionMixin.java#L77)
Mojmap makes this mistake much clearer:
![image](https://github.com/QuiltMC/quilt-standard-libraries/assets/60247969/6cc4f6a9-a935-445d-8ad8-27088e1ea61b)
`disconnect.genericReason` translates to `%s`, which should be filled in by the next string.
A recent update added methods that allow for a fallback when no translation is available. The wrong method is being used here.
This is one case I found, but there are probably more elsewhere. All uses should be checked.

**Comment by Patbox** [comment]
Updating mappings might fix that, as it was fixed there
