### ISSUE TITLE
Item Group Ordering is Random Each Startup

### ISSUE THREAD

**Issue by Oliver-makes-code** [QuiltMC/quilt-standard-libraries#327]
The order of item groups is randomized every time the game starts up.
I doubt it's mod load order, as even tabs from the same mod are in different positions and not guaranteed to be next to one another.

I propose that tabs are ordered by mod id (alphabetically) first, then the order within mods should be creation order

Screenshots (same world, same mods):
![2023-07-20_12 43 58](https://github.com/QuiltMC/quilt-standard-libraries/assets/59418903/6c6b46b9-cbf3-414a-8b1e-ee59f7c748dc)
![2023-07-20_12 54 09](https://github.com/QuiltMC/quilt-standard-libraries/assets/59418903/561dcde5-68d8-439f-9d46-cda45ec9c17b)

**Comment by Oliver-makes-code** [comment]
I'm using the blanketcon pack as it's most obvious there, but it occurs with a smaller subset of mods
I think it has somewhat to do with pages, though I'm not completely certain

**Comment by LambdAurora** [comment]
This should be investigated if it happens with Fabric API too with a Fabric-compatible mod set as currently QSL does not touch item groups.

**Comment by Jamalam360** [comment]
Patbox sent [this](https://github.com/FabricMC/fabric/pull/3222), so this can be closed
