### ISSUE TITLE
Nether in newly generated world does not gen properly if Nether was already visited in previous world

### ISSUE THREAD

**Issue by rinOfTheStars** [QuiltMC/quilt-standard-libraries#332]
See https://github.com/QuiltMC/quilted-fabric-api/issues/109, confirmed this is a bug in QSL in a dev environment. 

No clue what's actually causing this, but considering it only happens when the Nether has been generated in a previous world, something probably isn't getting cleared from memory properly?

**Comment by rinOfTheStars** [comment]
#333 should be a fix for this

**Comment by EnnuiL** [comment]
To be fixed on the next update!
