### ISSUE TITLE
error at startup

### ISSUE THREAD

**Issue by ghost** [QuiltMC/quilt-standard-libraries#335]
At startup, it starts with the loader version 0.19.2-beta.3 an error comes out:
error(https://drive.google.com/file/d/1qLnJFN8LSGSmmx3t0fPlz7xOJGfVtTzK/view?usp=sharing)
besides google, I have no other way to show the picture, excuse me

**Comment by LostLuma** [comment]
You're running an outdated version of quilt loader which causes this error. Make sure to select the newest one (`0.19.2`) since the modrinth launcher seems to not sort them properly.

Also for next time, you can simply press ctrl + v to paste files on GitHub and they will become part of your posts.

**Comment by OroArmor** [comment]
No update in 3 weeks, assuming fixed.
