### ISSUE TITLE
When will QSL & QFAPI for Minecraft 1.20.2 be released?

### ISSUE THREAD

**Issue by Jaffe2718** [QuiltMC/quilt-standard-libraries#352]
Minecraft 1.20.2 has been released quite a while ago, when will QFAPI & QSL be released for Minecraft 1.20.2?

**Comment by eristhea** [comment]
QSL has been updated. there's a tracking issue for QFAPI on its repository already: https://github.com/QuiltMC/quilted-fabric-api/issues/129
