### ISSUE TITLE
Bad mod compatibility with mixin into resource reloading

### ISSUE THREAD

**Issue by MattiDragon** [QuiltMC/quilt-standard-libraries#358]
QSL uses a mixin into `ServerReloadableResources#getReloaders` that injects its own reloaders into the vanilla system. For this it uses an unconditionally canceling mixin at `RETURN` which causes issues with other mixins (primarily from fabric mods without the same apis available). This issue is specifically bad as it depends on mod load order and causes mod resources to silently not be loaded due to QSL canceling the method before they get to do anything.

I suggest that this be fixed by replacing the mixin with a `@ModifyReturnValue` from mixin extras so that your modifications stack with those of other mods. The specific offending injector can be found [here](https://github.com/QuiltMC/quilt-standard-libraries/blob/c44d01ae6e7393a1ce4845cdc056475559c7e19e/library/core/resource_loader/src/main/java/org/quiltmc/qsl/resource/loader/mixin/ServerReloadableResourcesMixin.java#L43). 

Originally reported as MattiDragon/ExtendedDrawers#88.

**Comment by eristhea** [comment]
this has been fixed by https://github.com/QuiltMC/quilt-standard-libraries/commit/b10c5caad01928d2cecda1b0d94fb0b66c3fcfcb !
