### ISSUE TITLE
Energy API

### ISSUE THREAD

**Issue by theFFPS** [QuiltMC/quilt-standard-libraries#369]
Currently there is no unified energy API for Quilt. That means that every tech mod that will use Quilt modding API will write custom energy API or use existing one. But if there are two tech mods with different energy API and there is no energy conventer between them that will mean that there can't be any compatibility between energy source from one mod and machines from another and this a problem. This problem can be solved by creating unified energy API and this API can also simplify mod development by adding interfaces for energy storage, energy cable, energy generator and energy converter (adding compatibility with mods that have custom energy API). Also energy API will help with porting tech mods to Quilt (and adding support to existing tech mods that are using Quilt energy API without knowing about this mods).

**Comment by UpcraftLP** [comment]
The current de facto standard on fabric + quilt is https://github.com/TechReborn/Energy
