### ISSUE TITLE
Add a callback which is called for every instance of an object in a registry + future registrations.

### ISSUE THREAD

**Issue by i509VCB** [QuiltMC/quilt-standard-libraries#4]
Mirroring the idea of the `.all {` concept in gradle, we would add a event-like of method which runs the callback on all objects currently in the registry plus any future registrations. The use case here is reducing the duplicate functionality from iterating over the registry and then adding a registry event.

Example:
```java
RegistryEvents.all(Registry.BLOCK, (id, rawId, object) -> { ... });
```

**Comment by LambdAurora** [comment]
As suggested on Discord, something in the lines of `RegistryEvents.all(Registry.BLOCK, (id, rawId, block) -> { ... })`

Possible use case: https://github.com/LambdAurora/AurorasDecorations/blob/0989f46b0c9a037f4de056a1f042f1bcbbeb3352/src/main/java/dev/lambdaurora/aurorasdeco/registry/AurorasDecoRegistry.java#L459

**Comment by OroArmor** [comment]
#38

**Comment by LambdAurora** [comment]
This has been implemented.
