### ISSUE TITLE
QSL Versioning

### ISSUE THREAD

**Issue by TheGlitch76** [QuiltMC/quilt-standard-libraries#79]
What should QSL's versioning look like for the beta period of Quilt, before we are making stability guarantees?

We've already released modules as "1.0.0-SNAPSHOT", so we probably want to continue by using the prerelease system in semver.

However, the actual QSL meta-artifact is currently `0.1.0-SNAPSHOT`, so we could continue bumping the minor version of it for the time being.

Whatever we decide on, we should formalize it in a document in this repository.

**Comment by LambdAurora** [comment]
What is certain is Minecraft version metadata must be included to reduce confusion as `+<mc_version>`, this is already what is done.

**Comment by LambdAurora** [comment]
> However, the actual QSL meta-artifact is currently 0.1.0-SNAPSHOT, so we could continue bumping the minor version of it for the time being.

Just read semver, we can increment a number for each beta version
