### ISSUE TITLE
Resource loading does not allow `.` in names

### ISSUE THREAD

**Issue by OroArmor** [QuiltMC/quilt-standard-libraries#85]
https://github.com/QuiltMC/quilt-standard-libraries/blob/3f9d35b14268c94d816c8a9ee86ecd3941ce36ae/library/core/resource_loader/src/main/java/org/quiltmc/qsl/resource/loader/impl/ModNioResourcePack.java#L58

This violates the vanilla conventions for what is a valid namespace and identifier.

**Comment by LambdAurora** [comment]
![image](https://user-images.githubusercontent.com/12587332/158017760-286cb45f-682a-48e7-a3d8-d096aa823967.png)

Adding a test too.
