### ISSUE TITLE
`generateQmj` creates bad QMJs on non-release versions

### ISSUE THREAD

**Issue by triphora** [QuiltMC/quilt-standard-libraries#99]
As seen [here](https://github.com/QuiltMC/quilt-standard-libraries/blob/1.18/build-logic/src/main/java/qsl/internal/task/GenerateQmjTask.java#L30), the `generateQmj` gives `Versions.MINECRAFT_VERSION` for the MC dependency to use. However, on snapshot versions, `22w15a` (for example) is not a valid version identifier; `1.19-alpha.22.15.a` would have to be used instead.

**Comment by TheGlitch76** [comment]
We are focusing entirely on 1.18 for now, but I will try to fix this by the time 1.19 starts wrapping up!
